import type { NextPage } from "next";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Button from "@/components/Button";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-32 h-64 bg-red-200">
        <Button>hihih</Button>
      </div>
    </div>
  );
};

export default Home;
